export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  USERS: "/users",
  USER_DETAIL: "/users/:id",
  GROUPS: "/groups",
  GROUP_DETAIL: "/groups/:groupId",
  GROUP_SETTINGS: "/groups/:groupId/settings",
  GROUP_MEMBERS: "/groups/:groupId/members",
  GROUP_RESTAURANTS: "/groups/:groupId/restaurants",
  GROUP_RESTAURANT_DETAIL: "/groups/:groupId/restaurants/:restaurantId",
  GROUP_ORDERS: "/groups/:groupId/orders",
  GROUP_ORDER_DETAIL: "/groups/:groupId/orders/:orderId",
  GROUP_BALANCES: "/groups/:groupId/balances",
  NOT_FOUND: "*",
} as const;
